spring.application.name=couture-backend

# Configuration MongoDB
spring.mongodb.uri=mongodb+srv://ardaozanyildiz11_db_user:12851285Ay@stage.fbff9bj.mongodb.net/couture_db?retryWrites=true&w=majority&appName=Stage

# Configuration JavaMailSender (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aysunonder8080@gmail.com
spring.mail.password=cncrfmmgrlyounyn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true